using System.Collections.Generic;
using Dreamteck.Splines;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
#endif

/// <summary>
/// Editor-only authoring tool that forces the conveyor to actually look like its spline.
///
/// <para><b>Why this exists.</b> A conveyor spawned or reshaped by a script does not look like its
/// spline until two separate things are forced to happen, and neither happens on its own in edit
/// mode:
/// <list type="number">
/// <item><b>Tile count.</b> This is the one that matters. A Spline Mesh channel's <c>count</c> is
/// not a texturing detail — each repetition is one segment of the extrusion, and the belt's source
/// mesh has vertex groups only at its two ends, so the belt's authored count of 10 is literally a
/// 10-sided polygon however smooth the curve beneath it is. <see cref="SplineMeshAutoCount"/>
/// recomputes that count from the spline's length, but it is a plain MonoBehaviour: its
/// <c>Awake</c> never runs in edit mode, so the belt only becomes smooth the moment you press Play.
/// <b>Mesh Density</b> below applies the same formula from the button, so the editor shows exactly
/// what Play will build — and gives the collider the identical density, which nothing recomputes at
/// play time at all.</item>
/// <item><b>Component references.</b> Dreamteck's own editors call <c>EditorAwake()</c> when a
/// Spline Computer or Spline Mesh is selected, which re-acquires the MeshFilter/MeshRenderer/
/// MeshCollider that a rebuild writes into. That is why selecting the Conveyor by hand used to
/// "fix" a stale belt. This calls it directly, so no selection is needed.</item>
/// </list>
/// Press <b>Update Mesh</b> and the belt, collider, arrows and slots are all forced onto the
/// spline's current shape immediately.</para>
///
/// <para><b>Not a shape tool.</b> Unlike <c>ConveyorShapeBuilder</c> this never touches the spline's
/// points — it takes whatever shape is already on it, however it got there (hand-edited in the Scene
/// view, generated by the sandbox, or whatever else). It also does not add or remove slots or arrows;
/// it re-spaces whichever ones already exist, which is what makes it safe to run without a
/// <c>LevelSandbox</c>/<c>CarrierConfig</c> reference — attach it straight to the Conveyor prefab and
/// it works standalone.</para>
///
/// <para><b>Width Modifier / Side Wall Modifier.</b> Two independent scales over the same
/// cross-section, split by how each channel is authored. A channel authored dead-centre (its mesh
/// straddles the spline, offset zero either side — the belt's own single baked profile, and the
/// collider's Surface/Ceil) is the walkway: Width Modifier scales its mesh. A channel authored
/// off-centre (the collider's Left/Right walls, offset out from the centreline) is a side wall: Side
/// Wall Modifier scales how far out that offset sits instead, since scaling the wall's own mesh would
/// only stretch its profile without moving it. The belt mesh has no off-centre channel of its own, so
/// Side Wall Modifier only ever affects the collider. Either way the very first Update Mesh press
/// captures the untouched values as each modifier's baseline, so 1 always means "however the prefab
/// was authored," not an assumed 1-unit value, and pressing the button again at the same modifier is
/// a no-op rather than compounding.</para>
///
/// <para><b>Thickness Modifier.</b> A different knob to either of the above: it scales each spline
/// point's own <c>size</c> — the same value that drives the Spline Computer's "Draw Thickness" gizmo.
/// Spline Mesh multiplies every channel's mesh scale and offset by that point size at each vertex, so
/// this is the master scale Width Modifier and Side Wall Modifier are layered on top of; changing it
/// is the only way to change what the Draw Thickness gizmo shows. Same baseline-on-first-press, same
/// no-op-at-1 behaviour as the other two.</para>
///
/// <para><b>Editor only.</b> Every method lives inside <c>#if UNITY_EDITOR</c> and there is no
/// Awake/Start/Update, so nothing here can execute in a player build. The serialized fields
/// deliberately sit outside the guard so the component's serialized layout is identical in the editor
/// and in a build.</para>
/// </summary>
[DisallowMultipleComponent]
public sealed class ConveyorMeshUpdater : MonoBehaviour
{
    [System.Serializable]
    private struct ChannelWidthBase
    {
        public float ScaleX;
        public float MinOffsetX;
        public float MaxOffsetX;
    }

    // See the class summary for why these sit outside the UNITY_EDITOR guard.
#pragma warning disable CS0169, CS0414, CS0649

    [Header("References (auto-filled; drag only if this is not on the conveyor)")]
    [Tooltip("The conveyor's path. Auto-filled from this GameObject.")]
    [SerializeField] private SplineComputer _splineComputer;

    [Tooltip("The belt mesh that rides the spline. Auto-filled from this GameObject.")]
    [SerializeField] private SplineMesh _splineMesh;

    [Tooltip("The collider mesh (a child Spline Mesh, not this one). Auto-found among this " +
             "GameObject's children; drag one in if it was renamed in a way that confuses the search.")]
    [SerializeField] private SplineMesh _colliderMesh;

    [Tooltip("Auto-resolved from the scene's SceneScope Data list. Only needed to space slots by " +
             "Slot Collision Distance; without it slots are simply spread evenly over the length.")]
    [SerializeField] private ConveyorConfig _conveyorConfig;

    [Tooltip("The belt's own play-time tile-density driver. Auto-filled from this GameObject; this " +
             "is where Mesh Density reads its default from.")]
    [SerializeField] private SplineMeshAutoCount _autoCount;

    [Header("Density")]
    [Tooltip("Mesh tiles per world unit of spline. Each tile is one segment of the extrusion, so " +
             "this is what actually controls how smooth the belt is. Leave at 0 to use the belt's " +
             "own Spline Mesh Auto Count settings, which is what play mode applies — matching it " +
             "means the editor shows exactly what you will get on Play.")]
    [Min(0f)]
    [SerializeField] private float _meshDensity;

    [Tooltip("Allow the belt and collider meshes to use 32-bit indices. Unity's default 16-bit " +
             "index format caps a mesh at 65535 vertices; a long or dense conveyor blows straight " +
             "past that, and Dreamteck then logs \"exceeds the maximum vertex count\" and writes a " +
             "broken mesh. Leave this on unless you are targeting hardware without 32-bit index " +
             "support - the only cost is a slightly larger index buffer. Turn it off and lower Mesh " +
             "Density instead if you would rather keep the mesh small.")]
    [SerializeField] private bool _use32BitMeshIndices = true;

    [Header("Width")]
    [Tooltip("Scale of the belt's walkway (the collider's Surface/Ceil and the belt's own single " +
             "profile), relative to however it was authored (captured the first time Update Mesh " +
             "runs). 1 leaves it untouched. Does not move the side walls — see Side Wall Modifier.")]
    [Min(0.01f)]
    [SerializeField] private float _widthModifier = 1f;

    [Tooltip("How far out the collider's side walls sit from the centreline, relative to however " +
             "far out they were authored (captured the first time Update Mesh runs). 1 leaves them " +
             "untouched. The belt mesh has no separate wall channel, so this only ever moves the " +
             "collider — pair it with Width Modifier if the visible belt edge should move too.")]
    [Min(0.01f)]
    [SerializeField] private float _sideWallModifier = 1f;

    [Header("Thickness")]
    [Tooltip("Scale of the spline's own point size — the value driving the Spline Computer's " +
             "\"Draw Thickness\" gizmo, and the master scale Spline Mesh multiplies every channel's " +
             "width/offset by at each point. Relative to however each point was authored (captured " +
             "the first time Update Mesh runs). 1 leaves it untouched.")]
    [Min(0.01f)]
    [SerializeField] private float _thicknessModifier = 1f;

    [Header("Update")]
    [Tooltip("Also refit the collider mesh to the spline and to the current Width Modifier and Side " +
             "Wall Modifier. Turn this off only if the collider is being handled separately — " +
             "without it blocks can fall through or off the edge of a reshaped or resized belt.")]
    [SerializeField] private bool _updateCollider = true;

    [Tooltip("Re-space the existing arrows evenly over the new length. Their count is left exactly " +
             "as it already is.")]
    [SerializeField] private bool _updateArrows = true;

    [Tooltip("Re-space the existing slots onto the new spline. Their count is left exactly as it " +
             "already is. Note this moves the slots and any blocks authored under them in the " +
             "scene — at play time blocks are unparented and pushed by BlockPhysicsSystem instead, " +
             "which bakes its own path from the spline when the level builds.")]
    [SerializeField] private bool _updateSlots = true;

    // ── Width baseline (persisted; captured automatically, not hand-edited) ────────────────────
    [SerializeField, HideInInspector] private List<ChannelWidthBase> _beltWidthBase = new();
    [SerializeField, HideInInspector] private List<ChannelWidthBase> _colliderWidthBase = new();

    // ── Thickness baseline (persisted; captured automatically, not hand-edited) ───────────────
    [SerializeField, HideInInspector] private List<float> _pointSizeBase = new();

#pragma warning restore CS0169, CS0414, CS0649

#if UNITY_EDITOR

    private const string UpdateUndoName = "Update Conveyor Mesh";
    private const string SlotsRootName = "Slots";
    private const string ArrowsRootName = "Arrows";

    // Fills the references in when the component is first added, so dropping it on the Conveyor
    // prefab is all the setup there is.
    private void Reset()
    {
        ResolveReferences();
    }

    /// <summary>
    /// Fills in every reference that is still null and captures the width baseline if it has not
    /// been captured yet. Safe to call repeatedly; never overwrites something assigned by hand and
    /// never re-captures a baseline that already exists.
    /// </summary>
    public void ResolveReferences()
    {
        if (_splineComputer == null) _splineComputer = GetComponent<SplineComputer>();
        if (_splineMesh == null) _splineMesh = GetComponent<SplineMesh>();
        if (_colliderMesh == null) _colliderMesh = FindColliderMesh();
        if (_autoCount == null) _autoCount = GetComponent<SplineMeshAutoCount>();
        if (_conveyorConfig == null) _conveyorConfig = FindConveyorConfig();

        CaptureWidthBaseIfNeeded();
        CapturePointSizeBaseIfNeeded();
    }

    // Any Spline Mesh among the children that is not the belt's own — matches however the collider
    // object ends up named, since it is a separate prefab instantiated as a child at build time.
    private SplineMesh FindColliderMesh()
    {
        var meshes = GetComponentsInChildren<SplineMesh>(true);
        foreach (var mesh in meshes)
        {
            if (mesh == _splineMesh) continue;
            if (mesh.transform == transform) continue;
            return mesh;
        }

        return null;
    }

    // Same source of truth ConveyorShapeBuilder reads: the SceneScope Data list is private
    // serialized state, so it is read the same way, through SerializedObject.
    private ConveyorConfig FindConveyorConfig()
    {
        var scene = gameObject.scene;
        if (!scene.IsValid()) return null;

        SceneScope scope = null;
        foreach (var root in scene.GetRootGameObjects())
        {
            scope = root.GetComponentInChildren<SceneScope>(true);
            if (scope != null) break;
        }

        if (scope == null) return null;

        var so = new SerializedObject(scope);
        var dataProperty = so.FindProperty("_data");
        if (dataProperty == null) return null;

        for (var i = 0; i < dataProperty.arraySize; i++)
            if (dataProperty.GetArrayElementAtIndex(i).objectReferenceValue is ConveyorConfig config)
                return config;

        return null;
    }

    // ── Button: update ──────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Forces the spline to rebuild, then the belt mesh, then (if enabled) the collider, the arrows
    /// and the slots onto it — the whole reason this component exists. Blocks need no handling of
    /// their own: they are parented to their slot, so moving the slot carries them along.
    /// </summary>
    public void UpdateMesh()
    {
        ResolveReferences();

        if (!CanEdit()) return;
        if (_splineComputer == null || _splineMesh == null)
        {
            LogError("no Spline Computer or Spline Mesh on this GameObject. Attach this to the " +
                     "Conveyor prefab root.");
            return;
        }

        var toRecord = new List<Object> { _splineComputer, _splineMesh };
        if (_colliderMesh != null) toRecord.Add(_colliderMesh);
        Undo.RecordObjects(toRecord.ToArray(), UpdateUndoName);

        // Selecting these objects in the Hierarchy is what normally fixes a stale-looking belt —
        // Dreamteck's own SplineComputerEditor/SplineUserEditor call exactly this on OnEnable, which
        // re-acquires the MeshFilter/MeshRenderer/MeshCollider references RebuildImmediate() writes
        // into. Calling it here reproduces that without needing the user to click anything.
        EditorAwakeAll();

        // Must happen before either mesh is rebuilt below: the index format decides how many vertices
        // a mesh can hold at all, and a rebuild that overflows 16-bit indices writes a broken mesh.
        ApplyMeshIndexFormat();

        // Must happen before the spline rebuild below, so the forced rebuild bakes the new point
        // sizes into the spline's evaluate cache before the belt/collider meshes sample it.
        CapturePointSizeBaseIfNeeded();
        ApplyThickness();

        // Forced and immediate, not the deferred Rebuild() — this button exists specifically to show
        // the result without needing the Scene view to select anything.
        _splineComputer.RebuildImmediate();
        var length = _splineComputer.CalculateLength();

        CaptureWidthBaseIfNeeded();

        // Counts first: they decide how many segments the extrusion has, so they must be in place
        // before either mesh is told to rebuild.
        var tiles = ApplyTileCounts(length);

        ApplyWidth(_splineMesh, _beltWidthBase);
        _splineMesh.RebuildImmediate();
        MarkDirty(_splineMesh);

        var summary = new List<string> { $"spline rebuilt (length {length:F1})", tiles };

        if (_updateCollider)
        {
            if (_colliderMesh != null)
            {
                ApplyWidth(_colliderMesh, _colliderWidthBase);
                _colliderMesh.RebuildImmediate();
                MarkDirty(_colliderMesh);
                summary.Add("collider refitted");
            }
            else
            {
                summary.Add("no collider mesh found");
            }
        }

        if (_updateArrows) summary.Add(UpdateArrows(length));
        if (_updateSlots) summary.Add(UpdateSlots(length));

        MarkDirty(this);
        Log(string.Join(", ", summary) + ".");
    }

    // Re-acquires each SplineUser's cached MeshFilter/MeshRenderer/MeshCollider references the way
    // Unity's own SplineComputerEditor/SplineUserEditor do on OnEnable (SplineComputerEditor.cs:92,
    // SplineUserEditor.cs:351) — see MeshGenerator.EditorAwake(). Without this, RebuildImmediate()
    // can regenerate mesh data with nothing reliable to assign it to, which is why the belt used to
    // stay stale-looking until the Conveyor was selected by hand.
    private void EditorAwakeAll()
    {
        _splineComputer.EditorAwake();
        _splineMesh.EditorAwake();
        if (_colliderMesh != null) _colliderMesh.EditorAwake();
    }

    // ── Mesh index format ────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Puts the belt and collider meshes on the index format chosen by Use 32 Bit Mesh Indices.
    ///
    /// <para>Dreamteck's MeshGenerator defaults to 16-bit indices, which caps a mesh at 65535
    /// vertices and only reports the overflow after the fact (MeshGenerator.WriteMesh) — by which
    /// point it has already written a broken mesh. A conveyor long or dense enough to need this is
    /// exactly the kind this component exists to author, so the format is raised here rather than
    /// left to be found by hand in each Spline Mesh's Vertices foldout.</para>
    ///
    /// <para>Public because a reshaping tool must call it <i>before</i> it writes points: any
    /// SplineComputer.SetPoints rebuilds the meshes immediately, so a builder that waits for
    /// <see cref="UpdateMesh"/> to set the format has already overflowed once by then.</para>
    /// </summary>
    public void ApplyMeshIndexFormat()
    {
        var format = _use32BitMeshIndices
            ? UnityEngine.Rendering.IndexFormat.UInt32
            : UnityEngine.Rendering.IndexFormat.UInt16;

        if (_splineMesh != null) _splineMesh.meshIndexFormat = format;
        if (_colliderMesh != null) _colliderMesh.meshIndexFormat = format;
    }

    // ── Width ────────────────────────────────────────────────────────────────────────────────

    private void CaptureWidthBaseIfNeeded()
    {
        if (_beltWidthBase.Count == 0 && _splineMesh != null)
            _beltWidthBase = CaptureChannelBases(_splineMesh);

        if (_colliderWidthBase.Count == 0 && _colliderMesh != null)
            _colliderWidthBase = CaptureChannelBases(_colliderMesh);
    }

    private static List<ChannelWidthBase> CaptureChannelBases(SplineMesh mesh)
    {
        var channelCount = mesh.GetChannelCount();
        var result = new List<ChannelWidthBase>(channelCount);

        for (var i = 0; i < channelCount; i++)
        {
            var channel = mesh.GetChannel(i);
            var scaleX = channel.GetMeshCount() > 0 ? channel.GetMesh(0).scale.x : 1f;

            result.Add(new ChannelWidthBase
            {
                ScaleX = scaleX,
                MinOffsetX = channel.minOffset.x,
                MaxOffsetX = channel.maxOffset.x
            });
        }

        return result;
    }

    // A channel authored dead-centre (offset zero either side) is the walkway — Width Modifier scales
    // its mesh. A channel authored off-centre (the collider's Left/Right walls) is a side wall — Side
    // Wall Modifier scales how far out its offset sits instead, independently of the walkway, so the
    // two can be tuned apart (e.g. widen the safety margin between belt edge and wall without moving
    // the belt edge itself).
    private void ApplyWidth(SplineMesh mesh, List<ChannelWidthBase> bases)
    {
        if (mesh == null || bases == null) return;

        var channelCount = Mathf.Min(mesh.GetChannelCount(), bases.Count);
        for (var i = 0; i < channelCount; i++)
        {
            var channel = mesh.GetChannel(i);
            var baseValues = bases[i];

            var isCentered = Mathf.Approximately(baseValues.MinOffsetX, 0f) &&
                             Mathf.Approximately(baseValues.MaxOffsetX, 0f);

            if (isCentered)
            {
                if (channel.GetMeshCount() == 0) continue;
                var meshDef = channel.GetMesh(0);
                meshDef.scale = new Vector3(baseValues.ScaleX * _widthModifier, meshDef.scale.y, meshDef.scale.z);
            }
            else
            {
                channel.minOffset = new Vector2(baseValues.MinOffsetX * _sideWallModifier, channel.minOffset.y);
                channel.maxOffset = new Vector2(baseValues.MaxOffsetX * _sideWallModifier, channel.maxOffset.y);
            }
        }
    }

    // ── Thickness (the spline's own point size, not a channel value) ───────────────────────────

    private void CapturePointSizeBaseIfNeeded()
    {
        if (_pointSizeBase.Count != 0 || _splineComputer == null) return;

        _pointSizeBase = new List<float>(_splineComputer.pointCount);
        for (var i = 0; i < _splineComputer.pointCount; i++)
            _pointSizeBase.Add(_splineComputer.GetPointSize(i));
    }

    // Scales every point's size relative to its captured baseline. This is the value Spline Mesh
    // multiplies every channel's mesh scale and offset by at each vertex (see SplineMesh.Extrude),
    // and the same value the Spline Computer's Draw Thickness gizmo visualises — so unlike Width
    // Modifier/Side Wall Modifier, which only ever touch a channel's own authored scale/offset, this
    // is the only one of the three that actually changes what that gizmo shows.
    private void ApplyThickness()
    {
        if (_splineComputer == null || _pointSizeBase.Count == 0) return;

        // Every point is covered, not just the ones the baseline happens to have an entry for. A
        // reshaping tool (ConveyorPathBuilder, ConveyorRectangleBuilder) replaces the spline's points
        // wholesale and can easily leave more of them than were here when the baseline was captured;
        // those extra points used to fall outside the loop entirely and keep SplinePoint's default
        // size of 1, which is what made a long path visibly narrow partway along and then refuse to
        // respond to Thickness Modifier from that point on. A conveyor's thickness is uniform, so the
        // last captured value is the right one to carry across the remainder.
        for (var i = 0; i < _splineComputer.pointCount; i++)
        {
            var baseSize = _pointSizeBase[Mathf.Min(i, _pointSizeBase.Count - 1)];
            _splineComputer.SetPointSize(i, baseSize * _thicknessModifier);
        }
    }

    // ── Tile counts (the actual smoothness control) ──────────────────────────────────────────

    /// <summary>
    /// Tiles per world unit. An explicit Mesh Density wins; otherwise the belt's own
    /// <see cref="SplineMeshAutoCount"/> is the source of truth, because that is the number play
    /// mode will apply. Returns 0 when neither is available, in which case counts are left alone.
    /// </summary>
    private float ResolveDensity()
    {
        if (_meshDensity > 0f) return _meshDensity;

        var elements = _autoCount != null ? _autoCount.EditorElements : null;
        if (elements == null || elements.Count == 0) return 0f;

        return elements[0].LengthMultiplier;
    }

    // This is the fix for "smooth only after entering play mode". A channel's tile count is not a
    // texturing detail — each repetition is one segment of the extrusion, and the belt's source mesh
    // has vertex groups only at its two ends, so a count of 10 is literally a 10-sided polygon no
    // matter how smooth the spline underneath it is. SplineMeshAutoCount recomputes that count from
    // the spline's length at play time, but it is a plain MonoBehaviour, so its Awake never runs in
    // edit mode and the belt sits at whatever coarse count the prefab was saved with. Applying the
    // same formula here is what makes the editor show what Play will build.
    //
    // The collider is deliberately given the SAME density rather than the belt's raw count (which is
    // what the old code copied, dragging the collider down to the belt's stale 10): matching density
    // is what keeps the two 1:1 at any length, and nothing recomputes the collider at play time, so
    // this is its only chance to track a reshaped path.
    private string ApplyTileCounts(float length)
    {
        var density = ResolveDensity();
        if (density <= 0f) return "tile counts left as authored";

        var elements = _meshDensity > 0f ? null : _autoCount?.EditorElements;
        var beltCount = Mathf.Max(1, Mathf.CeilToInt(length * density));

        if (elements != null)
        {
            // Honour the per-channel mapping exactly, so the result is identical to what
            // SplineMeshAutoCount.UpdateMeshCount would produce the moment Play is pressed.
            foreach (var element in elements)
            {
                if (element.TargetChannelIdx < 0 || element.TargetChannelIdx >= _splineMesh.GetChannelCount())
                    continue;

                _splineMesh.GetChannel(element.TargetChannelIdx).count =
                    Mathf.Max(1, Mathf.CeilToInt(length * element.LengthMultiplier));
            }
        }
        else
        {
            for (var i = 0; i < _splineMesh.GetChannelCount(); i++)
                _splineMesh.GetChannel(i).count = beltCount;
        }

        if (_updateCollider && _colliderMesh != null)
        {
            for (var i = 0; i < _colliderMesh.GetChannelCount(); i++)
                _colliderMesh.GetChannel(i).count = beltCount;
        }

        return $"{beltCount} tiles at {density:F2}/unit";
    }

    // ── Arrows / slots ───────────────────────────────────────────────────────────────────────

    // Re-spaces whichever arrows already exist evenly over the new length. Never adds or removes —
    // that is ConveyorShapeBuilder's job, and doing it here would need ConveyorConfig.ArrowPrefab.
    private string UpdateArrows(double length)
    {
        var root = transform.Find(ArrowsRootName);
        if (root == null || root.childCount == 0) return "no arrows to update";

        var count = root.childCount;
        var spacing = (float)(length / count);
        var moved = 0;

        for (var i = 0; i < count; i++)
        {
            if (!root.GetChild(i).TryGetComponent<SplineFollower>(out var follower)) continue;

            Undo.RecordObject(follower, UpdateUndoName);
            follower.spline = _splineComputer;
            follower.SetPercent(_splineComputer.Travel(0d, spacing * i));
            MarkDirty(follower);
            moved++;
        }

        return $"{moved} arrow(s) re-spaced";
    }

    // Re-spaces whichever slots already exist — and with them the blocks parented under each slot —
    // using the same Travel-based formula LevelGeometry.ComputeSlotLayout uses, so a level that was
    // spaced by Slot Collision Distance stays spaced the same way after a reshape. Falls back to
    // even spacing when no ConveyorConfig could be resolved, so the button still does something
    // useful on a Conveyor with no scene config around it.
    private string UpdateSlots(double length)
    {
        var root = transform.Find(SlotsRootName);
        if (root == null || root.childCount == 0) return "no slots to update";

        var count = root.childCount;
        var usingConfig = _conveyorConfig != null && _conveyorConfig.SlotCollisionDistance > 0f;
        var slotDistance = usingConfig ? _conveyorConfig.SlotCollisionDistance : (float)(length / count);
        var moved = 0;

        for (var i = 0; i < count; i++)
        {
            if (!root.GetChild(i).TryGetComponent<SplineFollower>(out var follower)) continue;

            Undo.RecordObject(follower, UpdateUndoName);
            follower.spline = _splineComputer;
            follower.SetPercent(_splineComputer.Travel(0d, slotDistance * i));
            MarkDirty(follower);
            moved++;
        }

        return $"{moved} slot(s) re-spaced" + (usingConfig ? "" : " (no Conveyor Config, spaced evenly)");
    }

    // ── Plumbing ─────────────────────────────────────────────────────────────────────────────

    private bool CanEdit()
    {
        if (!EditorApplication.isPlayingOrWillChangePlaymode) return true;

        LogError("cannot update the conveyor mesh in play mode. Exit play mode and try again.");
        return false;
    }

    private static void MarkDirty(Object target)
    {
        if (target == null) return;

        EditorUtility.SetDirty(target);

        if (target is Component component && component.gameObject.scene.IsValid())
            EditorSceneManager.MarkSceneDirty(component.gameObject.scene);
    }

    private void Log(string message) => Debug.Log($"<b>Conveyor Mesh</b>: {message}", this);
    private void LogError(string message) => Debug.LogError($"<b>Conveyor Mesh</b>: {message}", this);

#endif
}
